books/books/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('head/', include(('head.urls', 'head'), namespace='head')),
]

books/head/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('home/', views.home, name='home'),
    path('create_book/', views.create_book, name='create_book'),
    path('delete_book/', views.delete_book, name='delete_book'),
    path('search_book/', views.search_book, name='search_book'),
    path('change_status/', views.change_status, name='change_status')
]

books/head/models.py
from django.db import models


STATUS = [('в наличии', 'в наличии'),
          ('выдана', 'выдана')]

class Book(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    author = models.CharField(max_length=255, null=True, blank=True)
    year = models.PositiveIntegerField(null=True, blank=True)
    status = models.CharField(max_length=255, choices=STATUS, blank=True)

books/head/forms.py
from django import forms
from .models import *

class BookForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(
        attrs= {'class': 'input'}
    ), label= 'Название книги')
    author = forms.CharField(widget=forms.TextInput(
        attrs= {'class': 'input'}
    ), label= 'Имя автора')
    year = forms.IntegerField(label='год издания')
    status = forms.ChoiceField(label='выберите статус', choices=STATUS)
    
    class Meta:
        model = Book
        fields = [
            'title',
            'author',
            'year',
            'status',
        ]

class DeleteBook(forms.ModelForm):
    pk=forms.IntegerField(label='Введите id')

    class Meta:
        model = Book
        fields = [
            'pk',
        ]

class ChangeStatusForm(forms.ModelForm):
    pk = forms.IntegerField(label='Введите id')
    status = forms.ChoiceField(label='выберите статус', choices=STATUS)

    class Meta:
        model = Book
        fields = [
            'pk',
            'status',
        ]

books/head/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.db.models import Q

def home(request):
    books = Book.objects.all()
    return render(request, 'home.html', {'books': books})

def create_book(request):
    form = BookForm(request.POST or None)
    if form.is_valid():
        form.save(commit=False)
        Book.objects.create(title=form.data['title'], author=form.data['author'], year=form.data['year'], status=form.data['status'])
        form.clean()
        return redirect('head:home')
    return render(request, 'create_book.html', {'form': form})

def delete_book(request):
    form = DeleteBook(request.POST or None)
    if form.is_valid():
        if Book.objects.filter(pk=form.data['pk']).exists():
            Book.objects.get(pk=form.data['pk']).delete()
        else:
            return render(request, 'error.html')
        return redirect('head:home')
    return render(request, 'delete_book.html', {'form': form})

def search_book(request):
    search = request.GET.get('search')
    if search:
        search_books = Book.objects.filter(Q(title__icontains=search) |
                                           Q(author__icontains=search) |
                                           Q(year__icontains=search))
    else:
        search_books = None
    return render(request, 'search_book.html', {'search_books': search_books})

def change_status(request):
    form = ChangeStatusForm(request.POST or None)
    if form.is_valid():
        book = Book.objects.filter(pk=form.data['pk'])
        if book.exists():
            book.update(status=form.data['status'])
            return redirect('head:home')
        else:
            return render(request, 'error.html')
    return render(request, 'change_status.html', {'form': form})

books/head/templates/change_status.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="">
        <a href="{% url 'head:home' %}">Назад</a>
    </div>
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <span>
        {% for field in form %}
            <div class="field">
                <label for="{{ field.id_for_label }}" class="label">
                    {{ field.label }}
                </label>
                <div class="control">
                    {{ field }}
                </div>
            </div>
            {% endfor %}
            {% if form.errors %}
                <ul>
                    {% for error in form.errors.values %}
                        <li class="">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </span>
        <span>
            <button>
                Изменить
            </button>
        </span>
    </form>
</body>
</html>

books/head/templates/create_book.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="">
        <a href="{% url 'head:home' %}">Назад</a>
    </div>
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="field">
                <label for="{{ field.id_for_label }}" class="label">
                    {{ field.label }}
                </label>
                <div class="control">
                    {{ field }}
                </div>
            </div>
        {% endfor %}
        {% if form.errors %}
            <ul>
                {% for error in form.errors.values %}
                    <li class="has-text-danger">{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <div>
            <button>
                Создать
            </button>
        </div>
    </form>
</body>
</html>

books/head/templates/delete_book.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="">
        <a href="{% url 'head:home' %}">Назад</a>
    </div>
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <span>
        {% for field in form %}
            <div class="field">
                <label for="{{ field.id_for_label }}" class="label">
                    {{ field.label }}
                </label>
                <div class="control">
                    {{ field }}
                </div>
            </div>
            {% endfor %}
            {% if form.errors %}
                <ul>
                    {% for error in form.errors.values %}
                        <li class="">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </span>
        <span>
            <button>
                Удалить
            </button>
        </span>
    </form>
</body>
</html>

books/head/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="">Книги с таким id не существует</div>
    <a href="{% url 'head:delete_book' %}">Назад</a>
</body>
</html>

books/head/templates/home.html
<!-- {% load static from static %} -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <title>
        Document
    </title>
</head>
<body>
    <div class="">
        <a href="{% url 'head:create_book' %}">Добавить книгу</a>
    </div>
    <div class="">
        <a href="{% url 'head:delete_book' %}">Удалить книгу</a>
    </div>
    <div class="">
        <a href="{% url 'head:search_book' %}">Найти книгу</a>
    </div>
    <div class="">
        <a href="{% url 'head:change_status' %}">Изменить статус книги</a>
    </div>
    <div class="" style="text-align: center;">
            {% for book in books %}
            <div>
                {{ book.pk }} {{ book.title }} {{ book.auther }} {{ book.year }} {{ book.status }}
            </div>
            {% endfor %}
    </div>
</body>
</html>

books/head/templates/search_book.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <title>Document</title>
</head>
<body>
    <a href="{% url 'head:home' %}">Назад</a>
    <form method="get">
        <div class="field has-addons">
            <span class="control">
                <input type="search" class="input" name="search">
            </span>
            <span class="control">
                <button class="button" type="submit">
                    <ion-icon name="search-outline"></ion-icon>
                </button>
            </span>
        </div>
    </form>
    <ul>
        {% for book in search_books %}
        <li>
            {{ book.pk }} {{ book.title }} {{ book.author }} {{ book.year }} {{ book.status }}
        </li>
        {% endfor %}
    </ul>
</body>
</html>